theme: jekyll-theme-cayman
title: Teapet
description: TeaPet is an all-in-one desktop program for primary school form teachers to manage their classroom effectively. It manages your personal curriculum schedule, student particulars, and can also track your class progress all in one simple program.
