@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyTeaPet <<Interface>>
Interface Model <<Interface>>
Interface ObservableList <<Interface>>
Class TeaPet
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs

Interface ReadOnlyAcademics <<Interface>>
Interface ReadOnlyAdmin <<Interface>>
Interface ReadOnlyNotes <<Interface>>
Interface ReadOnlyEvents <<Interface>>

Class Academics
Class Admin
Class NotesManager
Class EventHistory
Class UniqueStudentList
Class UniqueAssessmentList
Class UniqueDateList
Class UniqueNotesList

Academics .up.|> ReadOnlyAcademics
Admin .up.|> ReadOnlyAdmin
NotesManager .up.|> ReadOnlyNotes
EventHistory .up.|> ReadOnlyEvents
UserPrefs .up.|> ReadOnlyUserPrefs
TeaPet .left.|> ReadOnlyTeaPet


Package Student {
Class Student
Class Address
Class Email
Class Name
Class Phone
Class Temperature
Class NextOfKin
NextOfKin *--> NextOfKinName
NextOfKin *---> NextOfKinRelationship
NextOfKin *---> NextOfKinContact
}

Package Tag {
Class Tag
}
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

ModelManager .up.|> Model
Model .right.> ObservableList
ModelManager o--> "1" TeaPet
ModelManager o-right-> "1" Academics
ModelManager o-right-> "1" Admin
ModelManager o-left-> "1" NotesManager
ModelManager o-left-> "1" EventHistory
ModelManager o-right-> "1" UserPrefs

Academics *--> "1" UniqueAssessmentList
Admin *--> "1" UniqueDateList
NotesManager *--> "1" UniqueNotesList

TeaPet *--> "1" UniqueStudentList

UniqueStudentList o--> "*" Student
Student *--> Name
Student *--> Phone
Student *--> Email
Student *--> Address
Student *--> "*" Tag
Student *--> Temperature
Student *--> NextOfKin


Name -[hidden]right-> Phone
Phone -[hidden]right-> Address
Address -[hidden]right-> Email

@enduml
