@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package NotesManager {
Interface ReadOnlyNotes <<Interface>>
Class NotesManager
NotesManager .left.|> ReadOnlyNotes

Package Notes  {
Class UniqueNotesList
Class Notes
Notes *--> "1" StudentName
Notes *--> "1" Content
Notes *--> "1" Priority
Notes *--> "1" DateTime

NotesManager *--> "1" UniqueNotesList
UniqueNotesList o--> "0..*" Notes

@enduml
