@startuml
start
:User executes notes delete;
:Command gets parsed by logic component;
:Delete command gets executed;


'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([Valid index provided])
    :Deletes the note from storage;
    :Display delete success message;

else ([else])
        :Display invalid index provided message;

endif
stop
@enduml
