@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

Interface Storage <<Interface>>
Interface UserPrefsStorage <<Interface>>
Interface TeaPetStorage <<Interface>>
Interface AcademicsStorage <<Interface>>
Interface AdminStorage <<Interface>>
Interface NotesManagerStorage <<Interface>>
Interface EventStorage <<Interface>>

Class StorageManager
Class JsonUserPrefsStorage
Class JsonTeaPetStorage

Class JsonAcademicsStorage
Class JsonAdminStorage
Class JsonNotesManagerStorage
Class JsonEventStorage

StorageManager .left.|> Storage
StorageManager o--> UserPrefsStorage
StorageManager o--> TeaPetStorage
StorageManager o--> AcademicsStorage
StorageManager o--> AdminStorage
StorageManager o--> NotesManagerStorage
StorageManager o--> EventStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage

JsonTeaPetStorage .up.|> TeaPetStorage
JsonTeaPetStorage .down.> JsonSerializableTeaPet
JsonSerializableTeaPet --> "0..*" JsonAdaptedStudent

JsonAcademicsStorage .up.|> AcademicsStorage
JsonAcademicsStorage .down.> JsonSerializableAcademics
JsonSerializableAcademics --> "0..*" JsonAdaptedAssessment

JsonAdminStorage .up.|> AdminStorage
JsonAdminStorage .down.> JsonSerializableAdmin
JsonSerializableAdmin --> "0..*" JsonAdaptedDate

JsonNotesManagerStorage .up.|> NotesManagerStorage
JsonNotesManagerStorage .down.> JsonSerializableNotesManager
JsonSerializableNotesManager --> "0..*" JsonAdaptedNotes

JsonEventStorage .up.|> EventStorage
JsonEventStorage .down.> JsonSerializableEvents
JsonSerializableEvents --> "0..*" JsonAdaptedEvent

@enduml
