@startuml
start
:User executes admin save command;
:Parse the command;
:Save command gets executed;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([Date does not exist in storage])
    :Deletes the date from storage;
    :Show delete success message;

else ([else])
    if() then ([Data does exists in storage])
        :Show date not found message;

    else ([else])
        :Show parsing error message;
    endif
endif
stop
@enduml
