= Gary Lim Koon Yi - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: TeaPet

---

== Overview

TeaPet is a personal manager application for Form Teachers of Primary, Secondary and Tertiary institutions. The user interacts with it via
a Command Line Interface (CLI) along with a Graphical User Interface (GUI) created with JavaFX. The application is
written in Java.


== Summary of contributions

* *Major enhancement*: developed the *Personal Schedule* feature of TeaPet.
** *What it does*: Allows the user to keep track of all of his/her events by adding it as an Event in the Personal Schedule.
** *Justification*: This feature is an integral part in any teacher's routine applications. It provides a platform to track the user's
events that the user has to attend. We decided to integrate this feature into TeaPet because we feel that TeaPet should also be an application
that helps the user manage their time, on top of its primary functions of managing the user's class details. An integrated platform will ensure that our
product will help the user save time by only using TeaPet, since using different applications to keep track of different things is a hassle.
** *Highlights*: Users are able to add, edit and delete events scheduled in their personal scheduler. They can set recurring events and have different
color codes to represent different event types. Users can export their schedule to an .ics file to import into Google Calendar and other mainstream calendar applications.
Different view modes are also available for the Personal Schedule. The implementation was challenging as it required me to study the implementation of the library.
** *Credits*: JFXtras iCalendar API was used to help develop our Personal Schedule.

* *Minor enhancement*: Ensured code naming is coherent within the project.

* *Code contributed*: [https://nus-cs2103-ay1920s2.github.io/tp-dashboard/#search=garysyndromes&sort=groupTitle&sortWithin=title&since=2020-02-14&timeframe=commit&mergegroup=false&groupSelect=groupByRepos&breakdown=false[Functional and Test code]]
* *Other contributions*:

** Project management:
*** In charge of Integration, ensured product does not have bugs when features are merged together.
*** Cleaned up code base, removed unused code.
** Enhancements to existing features:
*** Deleted Student Remark feature (since it was not in use) (Pull requests https://github.com[#33], https://github.com[#34])
*** Wrote additional tests for existing features to increase coverage from 62% to 74% (Pull requests https://github.com[#36], https://github.com[#38])
** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide: (Pull requests https://github.com[#36], https://github.com[#38])
*** Updated User Guide to include Personal Schedule feature.
*** Updated User Guide introduction and format.
*** Updated Developer Guide to include Personal Schedule feature.
** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com[#12], https://github.com[#32], https://github.com[#19], https://github.com[#42]
*** Reported bugs and suggestions for other teams in the class (examples:  https://github.com/garysyndromes/ped[Practical Exam Dry Run])

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=delete]

include::../UserGuide.adoc[tag=dataencryption]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=undoredo]

include::../DeveloperGuide.adoc[tag=dataencryption]

