= Simon Lam - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

{nbsp} +

== Overview
---
TeaPet is a personal manager application for primary school form teachers. The user interacts with it via
a Command Line Interface (CLI) along with a Graphical User Interface (GUI) created with JavaFX. The application is
written in Java.

== Summary of contributions

This section entails a summary of my specific enhancements, code contributions and other helpful increments towards the TeaPet
application.

I implemented the student particulars feature, update student image feature, and part of the personal scheduler feature, which include:


=== Enhancements

== Student particulars

=== Student Creation and Deletion

* *What it does:* Users are able to add details of their students into the application. Students are created by specifying their
full names at the point of their creation. Additional details such as phone number, email, address, temperature and NOK details can be stored
in the application as well.

* *Justification:* Teachers usually have many students to spend their attention on, and having physical copies of a whole bunch
of data can be a hassle. With TeaPet, teachers can now enjoy the luxury of keeping track of all necessary details of their students
with just their laptop. There may also be a possibility where a teacher no longer teaches a student. Therefore, TeaPet
provides the functionality of removing students whom they no longer teach.

* *Highlights:* This enhancement allows the user to leave optional data unfilled. It might be quite difficult for teachers
to immediately gather all necessary details from students such as NOK particulars. Therefore, TeaPet allows the creation of students
to leave in empty optional fields. The only compulsory field is the name of the student.

=== Student editing

* *What it does:* Users are able to edit student details of students in the student list.

* *Justification:* There is always a possibility for teachers to key in information wrongly. Therefore, instead of
removing the student and creating a new one, TeaPet provides the functionality to simply edit the details of a student within
the student list.

=== Update Student Image

* *What it does:* Users are able to add in pictures of students into the student list.

* *Justification:* As mentioned, teachers usually have a large class of students and it may be quite challenging to remember
each of their name. Hence, TeaPet provides the functionality to update images of your students. This allows teachers to identify
students base of their pictures for easier recognition in classrooms, even if its their first few times meeting them.


== Personal Scheduler

=== Event Creation

* *What it does:* Users are able to create events and add them into their personal scheduler. These events are created
by specifying the event name, start time, end time.

* *Justification:* Teachers are always extremely busy and have many activities to attend. Some of which are teaching classes,
meetings with teachers, meeting with parents, consultations etc. I wanted to make a feature which are able to manage the
time of teachers effectively, both inside and outside of classrooms.

* *Highlights:* The events can be set to recur weekly, daily, or not at all, which
reduces the hassle of re-typing in repeated commands if they have to take part in a particular event everyday. The events
can also be color coded by users such that they can easily identify and categorise them in their personal schedule if
it gets too packed.

{nbsp} +

==== Code Contributed
Please click https://nus-cs2103-ay1920s2.github.io/tp-dashboard/#search=TheElectricBlender&sort=totalCommits%20dsc&sortWithin=title&since=2020-02-14&timeframe=commit&mergegroup=false&groupSelect=groupByRepos&breakdown=false&tabOpen=true&tabType=authorship&tabAuthor=TheElectricBlender&tabRepo=AY1920S2-CS2103T-W12-2%2Fmain%5Bmaster%5D[here] to see my code contributions dashboard.

=== Other contributions
* Project management:

** Team lead of the project, ensuring everyone is up to date and on the same page for the tasked project.
** In charge of defining, assigning, and tasking of project tasks.
** Ensures project deliverables are done on time.

* Documentation:
** Updated User Guide to include Student, Schedule and Additional features. (Pull requests https://github.com/AY1920S2-CS2103T-W12-2/main/pull/49[#49], https://github.com/AY1920S2-CS2103T-W12-2/main/pull/216[#216], https://github.com/AY1920S2-CS2103T-W12-2/main/pull/217[#217], https://github.com/AY1920S2-CS2103T-W12-2/main/pull/225[#225], https://github.com/AY1920S2-CS2103T-W12-2/main/pull/242[#242])
** Updated User Guide with a simple and easy to use Command Summary page.
** Updated User Guide with a product survey: (Pull requests https://github.com/AY1920S2-CS2103T-W12-2/main/pull/62[#62])
** Updated Developer Guide to include Student, Schedule and Additional features. (Pull requests https://github.com/AY1920S2-CS2103T-W12-2/main/pull/245[#245], https://github.com/AY1920S2-CS2103T-W12-2/main/pull/251[#251])

* Community
** PRs reviewed (with non-trivial review comments): https://github.com/AY1920S2-CS2103T-W12-2/main/issues/30[#30], https://github.com/AY1920S2-CS2103T-W12-2/main/pull/66[#66], https://github.com/AY1920S2-CS2103T-W12-2/main/pull/67[#67]
** Reported bugs and suggestions for other teams in the class: (Examples: https://github.com/TheElectricBlender/ped/issues[PE Dry Run])

* Tools
** Integrated a Github plugin (Coverall) to the team project https://github.com/AY1920S2-CS2103T-W12-2/main/pull/259[#259]
** Integrated a Github plugin (Travis) to the team project https://github.com/AY1920S2-CS2103T-W12-2/main/pull/265[#265]
** Integrated a Github plugin (Netlify) to the team project https://github.com/AY1920S2-CS2103T-W12-2/main/pull/265[#265]
** Integrated a third party library (iCalendarAgenda) to the project https://github.com/AY1920S2-CS2103T-W12-2/main/pull/108[#108]

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=navigate]
include::../UserGuide.adoc[tag=particulars]
include::../UserGuide.adoc[tag=scheduler-A]
include::../UserGuide.adoc[tag=additional-features]
include::../UserGuide.adoc[tag=ScheduleSummary]


== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=particulars-feature]
include::../DeveloperGuide.adoc[tag=class-overview-scheduler]
include::../DeveloperGuide.adoc[tag=uc-simon]
include::../DeveloperGuide.adoc[tag=uc-simon2]
include::../DeveloperGuide.adoc[tag=manual-test-particulars]
include::../DeveloperGuide.adoc[tag=manual-test-scheduler]




