= Zhang Yuanyu - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: TeaPet

---

== Overview

TeaPet is a personal manager application for primary school form teachers. The user interacts with it via
a Command Line Interface (CLI) along with a Graphical User Interface (GUI) created with JavaFX. The application is
written in Java and only Java 11 supports this application. TeaPet is meant for online tracking purposes. With that
being said, there are future plans to expand the application to an online version.

== Summary of contributions

* *Major enhancement*: added *the ability for form teachers to track administrative information of the class*
** What it does: The form teacher will be able to save, delete and view administrative details of the class.
** Justification: The form teacher has to record administrative information of the class daily, hence this feature is essential for that purpose. With this feature, the form teacher can easily track
the administrative information of the class whenever and wherever.
** Highlights: This enhancement allows teachers to only save the most updated administrative list as today's date to prevent mutability of other dates. The teacher is also able to view
the dates that contains administrative information of the class.


* *Minor enhancement*: Added a temperature and attendance attribute to student class with the necessary restraints

* *Minor enhancement*: Changed the way student edit function works. Previously, editing one field of the student results in that field to be edited and the rest being changed back to default value.
Now, editing one field of the student still updates that specific field, but the rest of the fields are left untouched.

* *Code contributed*: [https://nus-cs2103-ay1920s2.github.io/tp-dashboard/#search=Yuanyu97&sort=groupTitle&sortWithin=title&since=2020-02-14&timeframe=commit&mergegroup=false&groupSelect=groupByRepos&breakdown=false[Functional code and Test code]]_

* *Other contributions*:

** Project management:
*** Git master of the project. Managed the team's repository and was in charge of the managing of the pull requests to prevent unnecessary merging of pull requests.
*** Helped teammates to fix their errors that resulted in travis build to fail.
*** Helped teammates with testing errors.
*** Explained to teammates the flow of AB3 to better help them understand the code and therefore aiding them in implementing their own features.
** Enhancements to existing features:
*** Loosened the restrain of tags to allow better flexibility of creating a tag (Pull request https://github.com/AY1920S2-CS2103T-W12-2/main/pull/228/files[#228])
** Documentation:
*** Updated User Guide to include Admin feature
*** Updated User Guide with FAQs and the glossary
*** Updated Developer Guide to include Admin feature
** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com/AY1920S2-CS2103T-W12-2/main/pull/118[#118], https://github.com/AY1920S2-CS2103T-W12-2/main/pull/112[#112], https://github.com/AY1920S2-CS2103T-W12-2/main/pull/96[#96], https://github.com/AY1920S2-CS2103T-W12-2/main/pull/78[#78],
https://github.com/AY1920S2-CS2103T-W12-2/main/pull/74[#74], https://github.com/AY1920S2-CS2103T-W12-2/main/pull/67[#67]
*** Contributed to forum discussions: https://github.com/nus-cs2103-AY1920S2/forum/issues/12[12]
*** Reported bugs and suggestions for other teams in the class: https://github.com/Yuanyu97/ped[Practical Exam Dry Run]

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=delete]

include::../UserGuide.adoc[tag=dataencryption]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=undoredo]

include::../DeveloperGuide.adoc[tag=dataencryption]
